### ISSUE TITLE
Implement cross-validation examples for Optuna Terminator 🤖

### ISSUE THREAD

**Issue by g-votte** [optuna/optuna-examples#182]
[Optuna Terminator](https://github.com/optuna/optuna/issues/4398) is a new feature planned to be introduced in the upcoming minor release, Optuna v3.2.

In particular, it is expected to help mitigate excessive resource usage and hyperparameter overfitting in cross-validation scenarios.

This issue aims to create example code demonstrating the usage of Optuna Terminator with ML libraries that support cross-validation. For instance:

- scikit-learn
- LightGBM
- XGBoost
- CatBoost

**Comment by nzw0301** [comment]
Is there an official document for this feature? It would be great to refer to the docs for contributors working on this issue.
