### ISSUE TITLE
Trial Fail

### ISSUE THREAD

**Issue by BaiMeiyingxue** [optuna/optuna-examples#196]
Hi, I'm a beginner of optuna, and here I encounter the error
![image](https://github.com/optuna/optuna-examples/assets/53547009/63ebb720-403b-46b7-928f-7140cb02323c)
the code is like below
```
    optuna.storages.RDBStorage("sqlite:///optuna1.db", skip_table_creation=False)
    storage_name = "sqlite:///optuna1.db"
    study = optuna.create_study(
        pruner=optuna.pruners.MedianPruner(n_warmup_steps=3), direction="maximize",
        study_name="fashion_mnist_torch", storage=storage_name,load_if_exists=True
    )
    study.optimize(objective, n_trials=20, timeout=1200)
    pruned_trials = study.get_trials(deepcopy=False, states=[TrialState.PRUNED])
    complete_trials = study.get_trials(deepcopy=False, states=[TrialState.COMPLETE])

```
Could you tell me why the trial is failed? Thank you very much!

**Comment by nzw0301** [comment]
Could you use https://github.com/optuna/optuna/discussions to ask a question? In addition, when you ask a question please kindly share the minimal reproducible code with us/
