### ISSUE TITLE
License of the optuna-examples repo?

### ISSUE THREAD

**Issue by visuallization** [optuna/optuna-examples#199]
Hi Optuna devs,

I was wondering what the license is of the optuna-examples repo and if it is okay to host an updated and customized version of the sb3_simple.py in our repo: https://github.com/edbeeching/godot_rl_agents/pull/ ?

Cheers,
Florentin

**Comment by not522** [comment]
Thank you for pointing this out. We have added the missing LICENSE file (#200), and this repository is licensed under the MIT License now (same as the Optuna repository).

**Comment by visuallization** [comment]
@not522 Thanks! :)
