### ISSUE TITLE
Add isort to CI

### ISSUE THREAD

**Issue by Crissman** [optuna/optuna-examples#23]
## Description

Add isort to CONTRIBUTING.md and add to CI tests

## Alternatives (optional)

Leave as is. This may be useful if some of our examples are replicated to other repositories, such as Chainer, to keep both versions identical

**Comment by jrbourbeau** [comment]
It looks like this was added in https://github.com/optuna/optuna-examples/pull/25. It's probably safe to close this issue

**Comment by nzw0301** [comment]
@jrbourbeau Thank you for letting us know about it!
