### ISSUE TITLE
 Add Python 3.12 to the CI

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna-examples#230]
## Motivation

Sub-task of https://github.com/optuna/optuna/issues/5000.

## Description

see the title of this issue.

## Additional context (optional)

Here is a list of the target yaml files under [`.github/workflows`](https://github.com/optuna/optuna-examples/tree/main/.github/workflows).

- [x] `aim.yml`
- [x] `allennlp.yml`
- [x] `base.yml`
- [x] `catboost.yml`
- [x] `chainer.yml`
- [x] `checks.yml`
- [x] `dashboard.yml`
- [x] `dask.yml`
- [x] `dask_ml.yml`
- [x] `fastai.yml`
- [ ] `haiku.yml`
- [x] `hiplot.yml`
- [x] `hydra.yml`
- [x] `keras.yml`
- [ ] `lightgbm.yml`
- [x] `mlflow.yml`
- [x] `multi_objective.yml`
- [x] `mxnet.yml`
- [x] `pytorch.yml`
- [x] `ray.yml`
- [x] `rl.yml`
- [x] `samplers.yml`
- [x] `skimage.yml`
- [x] `sklearn.yml`
- [x] `stale.yml`
- [x] `tensorboard.yml`
- [x] `tensorflow.yml`
- [x] `terminator.yml`
- [ ] `tfkeras.yml`
- [x] `visualization.yml`
- [x] `wandb.yml`
- [x] `xgboost.yml`

I've checked listings addressed by https://github.com/optuna/optuna-examples/pull/214 and have not removed the deprecated library's examples yet.

**Comment by Alnusjaponica** [comment]
Following libraries have been already archived will not support python 3.12.
- allennlp
- chainer
- mxnet

Following libraries does not (officially) support python 3.12 for now.
- aim https://github.com/aimhubio/aim/issues/3111
- fastai, haiku, lightgbm, mlflow (the CI does not run on python 3.11 and 3.12)
- keras, tensorboard, tensorflow, tfkeras https://github.com/tensorflow/tensorflow/issues/62003
- ray https://github.com/ray-project/ray/issues/40211

Following libraries have newly supported python 3.12 recently.
- catboost https://github.com/catboost/catboost/issues/2510
- dask https://github.com/dask/dask/pull/10544
- pytorch https://github.com/pytorch/pytorch/issues/110436
- wandb https://github.com/wandb/wandb/issues/6468

**Comment by nzw0301** [comment]
I investigated the current status of unaddressed items above:

### tfkeras

It works w/ python 3.12 but the examples shows warning message every trial as follows:

```shell
python tfkeras/tfkeras_integration.py

...
2024-08-03 14:53:51.516660: W tensorflow/core/kernels/data/cache_dataset_ops.cc:913] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.
```

```shell
python tfkeras/tfkeras_integration.py

...
2024-08-03 14:53:51.516660: W tensorflow/core/kernels/data/cache_dataset_ops.cc:913] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.
```

Similarly, `tfkeras/tfkeras_simple.py` shows warning message at the first model construction: 

```shell
python tfkeras/tfkeras_simple.py
[I 2024-08-03 14:59:38,046] A new study created in memory with name: no-name-b1748d29-9666-4ad1-96d8-2d95c2ea4b00
/opt/homebrew/Caskroom/miniconda/base/envs/optuna-312/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
```


### ray

Still ongoing task according to https://github.com/ray-project/ray/issues/40211.

**Comment by nzw0301** [comment]
[haiku repo](https://github.com/google-deepmind/dm-haiku) says it will support newer python but its CI does not use python 3.12 for white and it looks sort of maintenance mode, so I'd like to say let's close this issue without adding haiku 3.12 after merging #289 and #290.
