### ISSUE TITLE
NSGAIISampler number trials per generation

### ISSUE THREAD

**Issue by bartuilkilic** [optuna/optuna-examples#246]
Hello, 

I am new to the Optuna's NSGA-II algorithm and I want to us it for a project but I have some questions regarding the features.

As far as I understood from the NSGA-II, population size(parameter of NSGA-II) is the number of trials per generation. If the population_size = 50(default), it will continue every generation with 50 trials. My problem is, before starting the evaluation of the trials, I need to send them to another flow, so that I can generate the real data which will be optimized. But I couldn't find a way get the 50 trials and evaluate them then continue with the new generation.

I can parallelize Optuna maximum 5 times because of my other program licenses, so in the best case, I need the NSGA-II to return 10 trials per generation.

Is it possible to do it? If it is, can you point me how to do this?

Thanks in advance

**Comment by nzw0301** [comment]
Could you post this at https://github.com/optuna/optuna/discussions? Your question is not about optuna-example.
