### ISSUE TITLE
Is there a way to tell where a trail derives from?

### ISSUE THREAD

**Issue by aEgoist** [optuna/optuna-examples#273]
If I know it right, a new trial comes from several previous trials, which discovered the nearby space and suggested this new point of param combinations. Thus, I want to know if there's a way to know which one or two parent trials comes to this new trial, or say where it derives from, is it achieveable now?
In most cases, it's the nearest point in space from previous trials, we just need a way to find it out.
I think it's a good thing to know this, much like taking the procedure out of blackbox.

**Comment by nzw0301** [comment]
I suppose this issue is not a feature request for optuna example. Could you use https://github.com/optuna/optuna/discussions for asking a question on optuna.
