### ISSUE TITLE
Bug: Update optuna-integration in dask_simple.py

### ISSUE THREAD

**Issue by saldanhad** [optuna/optuna-examples#283]
With reference to (https://github.com/dask/dask/issues/11270). Update example in `dask_simple.py` to reflect recent changes to optuna-integration.

## Expected behavior

Add import statement 
` from optuna_integration import DaskStorage `

https://github.com/optuna/optuna-examples/blob/cec304012c8bb1d091d8b406999aab4075379cd7/dask/dask_simple.py#L41

Update above line of code as:
`  storage = DaskStorage()`

## Environment

- Optuna version: 4.0.0
- Python version: 3.10.12

**Comment by nzw0301** [comment]
Did you see the error message? In my understanding `optuna.integration.dask.DaskStorage`
 should be oaky because of https://github.com/optuna/optuna/blob/master/optuna/integration/dask.py.

**Comment by nzw0301** [comment]
I can ran the script, so this is not the bug.
