### ISSUE TITLE
Add missing examples to daily CI

### ISSUE THREAD

**Issue by hvy** [optuna/optuna-examples#3]
Some examples are not tested by the daily CI. All examples in this repository preferably should. See https://github.com/optuna/optuna-examples/pull/1#issuecomment-837856331.

**Comment by hvy** [comment]
This recent contribution as well https://github.com/optuna/optuna-examples/pull/11

**Comment by hvy** [comment]
- [ ] kubernetes/
- [ ] multi_objective/
- [ ] samplers/
- [ ] visualization/
- [ ] enqueue_trial.py
- [ ] max_trials_callback.py
- [ ] quadratic_simple.py
- [ ] quickstart.ipynb
- [ ] rapids_simple.py
- [ ] ray_joblib.py
- [ ] simple_pruning.py
- [ ] skimage_lbp_simple.py

**Comment by Crissman** [comment]
Implemented most. Ray, Kubernetes, the two `.ipynb` files, and Rapids are not implemented. Checking if Ray and the .ipynb files can be made to work. Assume testing Kubernetes within a docker or rapids not worth effort to add to CI.

**Comment by hvy** [comment]
Thanks for the updates, I'll have a look at #26. For the RAPIDS example, we could just CI check if it compiles. https://docs.python.org/3.8/library/py_compile.html

```python
python -m py_compile rapids_simple.py
```

As for the Kubernetes example, I don't think that it's urgent, but am wondering if we shouldn't leave it as an open issue.

**Comment by Crissman** [comment]
As suggested, made rapids a compile check only. I worked on ray_joblib.py a bit, but was unable to get the test to run on github actions. Apparently, unless running on python 3.7, it gives this error:
```
| ERROR: Could not find a version that satisfies the requirement ray (from versions: none)
| ERROR: No matching distribution found for ray
```

Even limiting to only python 3.7, I had a `domain error` on in the github workflow. Google search on the error did not show a clear approach, so I'm leaving as compile only, and marking this issue contribution welcome in case someone more familiar with ray wants to work on this.

**Comment by toshihikoyanase** [comment]
@hvy and @Crissman discussed the daily CI for Ray and RAPIDS last year, but no one investigates the `kubernetes` and `quickstart.ipynb`. I briefly checked them. I'm not familiar with them, so please correct me if I'm wrong.

### `kubernetes/`

The kubernetes example uses minikube, and minikube provides the [official guide](https://minikube.sigs.k8s.io/docs/tutorials/setup_minikube_in_github_actions/) to setup minikube as CI step in GitHub Actions. It may help us create daily CI for the kubernetes examples.


### `quickstart.ipynb`

[`papermill`](https://github.com/yaananth/papermill) says that it enable us to execute IPython notebook via Python API as follows:

```python
import papermill as pm

pm.execute_notebook(
   'path/to/input.ipynb',
   'path/to/output.ipynb',
   parameters = dict(alpha=0.6, ratio=0.1)
)
```

It may help us create daily CI for `quickstart.ipynb`. Also, we can see third-party github action to run notebook using papermil.
I'm not sure if we can use it in terms of security.
https://github.com/marketplace/actions/run-notebook

**Comment by toshihikoyanase** [comment]
@nzw0301 Thank you for your comment. Then, we can apply `jupyter nbconvert` to `quickstart.ipynb`!
