### ISSUE TITLE
Add `WeightsAndBiasesCallback` example

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna-examples#41]
## Motivation

Optuna introduces W&B integration, [`WeightsAndBiasesCallback`](https://optuna.readthedocs.io/en/latest/reference/generated/optuna.integration.WeightsAndBiasesCallback.html#optuna.integration.WeightsAndBiasesCallback) to track optimisation since the next version update, v2.9.0. By following our convention, it would be great to provide an example code to use the callback functionality. 

## Description

The expected pull request contains 

1. minimal example code like [`mlflow/keras_mlflow.py`](https://github.com/optuna/optuna-examples/blob/main/mlflow/keras_mlflow.py)
2. `README.md` like [`mlflow/README.md`](https://github.com/optuna/optuna-examples/tree/main/mlflow); 
3. Add weights and biases to [`README.md`](https://github.com/optuna/optuna-examples/blob/main/README.md)

Of course, `weightsandbiases/requirement.txt` and `.github/workflows/weightsandbiases.yml` are necessary.

## Additional context (optional)

Add W&B's link from the main repository: 

- https://github.com/optuna/optuna#integrations
- https://github.com/optuna/optuna/tree/master/examples

**Comment by xadrianzetx** [comment]
Will pick it up soon!

**Comment by nzw0301** [comment]
Oh, I realised that mlflow's example is not using `MLflowCallback` at all. It might not be a good example. Nevertheless, #55's example looks great. Thanks! @xadrianzetx

**Comment by xadrianzetx** [comment]
Yeah, I'll add callback example to mlflow after #55 :smile:

**Comment by nzw0301** [comment]
Amazing! I've just created issue #56 as a record.
