### ISSUE TITLE
Example of distribute training with TensorFlow.

### ISSUE THREAD

**Issue by keisuke-umezawa** [optuna/optuna-examples#48]
## Motivation

Currently, we do not have an example of distribute training with TensorFllow. It is useful for TensorFlow users.

https://www.tensorflow.org/guide/distributed_training

## Description

Create an example of distribute training with TensorFllow.

**Comment by toshihikoyanase** [comment]
I'm not familiar with tensorflow-ecosystem, but this [Keras distributed training tutorial](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras) provides more concrete code example than the [tensorflow's document](https://www.tensorflow.org/guide/distributed_training). In the tutorial, a simple convolutional neural network is trained with MNIST dataset in parallel.

So, how about creating the keras distributed example based on the tutorial, and then translate it using tensorflow APIs?
@keisuke-umezawa @hvy
 
CC @sfujiwara Please feel free to add any comments on this topic.

**Comment by keisuke-umezawa** [comment]
> So, how about creating the keras distributed example based on the tutorial, and then translate it using tensorflow APIs?

That's a better idea!
