### ISSUE TITLE
Consider introducing type hints and mypy

### ISSUE THREAD

**Issue by hvy** [optuna/optuna-examples#6]
Consider adding type hints to the code and run mypy in the CI (`optuna` itself has type hints). In addition to the static checking, type hints acts as documentation. The downside is that it will increase maintenance cost.

**Comment by hvy** [comment]
See also https://github.com/optuna/optuna/issues/2165.

**Comment by Crissman** [comment]
This is a good idea and would bring the examples in line with the optuna/optuna code. This doesn't need to be done all at once, so we welcome contributors to work on adding type hints and mypy compatibility on a example by example basis.
