### ISSUE TITLE
Deprecation Waring on KearsPruningCallback - How to implement it in a modern way?

### ISSUE THREAD

**Issue by JakobEliasWagner** [optuna/optuna-examples#60]
I was just reading up on how to implement pruning with otuna. I have based my implementation very closely on the methodology listed in example `keras/keras_integration.py`.
When running this code I get the following warning:
```
FutureWarning: KerasPruningCallback has been deprecated in v2.1.0. This feature will be removed in v4.0.0. See https://github.com/optuna/optuna/releases/tag/v2.1.0. Recent Keras release (2.4.0) simply redirects all APIs in the standalone keras package to point to tf.keras. There is now only one Keras: tf.keras. There may be some breaking changes for some workflows by upgrading to keras 2.4.0. Test before upgrading. REF:https://github.com/keras-team/keras/releases/tag/2.4.0
  callbacks=[KerasPruningCallback(trial, "loss")]
```
I was wondering what the futere-proof way of implementing this would be.
Thank you!

**Comment by nzw0301** [comment]
I think tfkeras's callback, https://optuna.readthedocs.io/en/stable/reference/generated/optuna.integration.TFKerasPruningCallback.html is the best alternative.
the example is found at https://github.com/optuna/optuna-examples/blob/main/tfkeras/tfkeras_integration.py.

**Comment by JakobEliasWagner** [comment]
Oh yeah it is. Sorr, I was not paying attention to the package and got them confused - Thank you so much for your answer!
