### ISSUE TITLE
Get best_iteration from best_trial using LighGBM

### ISSUE THREAD

**Issue by borisRa** [optuna/optuna-examples#70]
Hi,

I am using Optuna to optimize LightGBM parameters  with "valid_sets" like this :
`pruning_callback = optuna.integration.LightGBMPruningCallback(trial = trial, metric = conf_obj.losses_function_optimize.lower()) `

`lgbm_model = lgbm.train(params = param_grid, train_set = train_data_Dataset, valid_sets =[valid_data_Dataset], callbacks=[pruning_callback] , early_stopping_rounds = 10, verbose_eval=False)`

1) Is there an option to retrieve best_iteration from best model (based on  early_stopping_rounds )? 
2) Is there any sense to use ' early_stopping_rounds' functionality at all ?

Thanks,
Boris

**Comment by nzw0301** [comment]
Hi, could you share minimal reproducible codes with us?

**Comment by nzw0301** [comment]
Since this issue is not active for while, let me close this issue. If you have a question please use github discussions, https://github.com/optuna/optuna/discussions.
