### ISSUE TITLE
Improve catboost example

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna-examples#78]
Hyperparameter search space can improve by following the CatBoost's docs: https://catboost.ai/en/docs/concepts/parameter-tuning. In addition, it might be great to unify the code to the CatBoost example and the other boosting libraries.

_Originally posted by @nzw0301 in https://github.com/optuna/optuna-examples/issues/27#issuecomment-1005760194_

**Comment by tohmae** [comment]
I created a pull request to the CatBoost's docs: https://catboost.ai/en/docs/concepts/parameter-tuning.
https://github.com/catboost/catboost/pull/2000

**Comment by nzw0301** [comment]
Awesome. Thanks!

**Comment by liaison** [comment]
hi @nzw0301 is this issue resolved? If not, were you referring to [this example](https://github.com/catboost/tutorials/blob/master/hyperparameters_tuning/hyperparameters_tuning_using_optuna_and_hyperopt.ipynb) when you mentioned about unifying the examples?

**Comment by nzw0301** [comment]
Thank you for sharing it! I didn't notice such a notebook in the catboost repo. I think it would be great to mention the tutorial from the example at least.

**Comment by nzw0301** [comment]
> is this issue resolved?
Not sure. I'll check the status of this issue later. Thanks!
